// Published playtest data. When this file contains window.CUSTOM_DATA, every
// visitor gets that version of the cards/rules as their defaults.
// It is (re)generated by "Publish update.command" from your in-app Export —
// don't edit by hand unless you know what you're doing.
