#!/bin/zsh
# Publish your latest playtest changes to the shared GitHub Pages link.
#
# Two ways to make changes — both end with double-clicking this file:
#   A) Rules-document workflow (your Claude "Mortalis: Realms" project):
#      update the doc there, download it (lands in Downloads), then run this.
#      The whole card database + rule text is rebuilt from the doc.
#   B) In-app workflow: edit cards/rules inside the playtest app, click
#      Export (lands in Downloads), then run this.
#
# If a downloaded rules doc is newer, it wins — it becomes the single source
# of truth and older in-app exports are ignored.

cd "$(dirname "$0")" || exit 1
echo "=== Mortalis: Realms — publish update ==="
DOC_IMPORTED=""

# 1. Newest downloaded rules document (any .md with "mortalis" + "rules" in the name)
DOC=$(find ~/Downloads -maxdepth 1 -iname '*mortalis*rules*.md' -newer rules_current.md 2>/dev/null | xargs -I{} stat -f '%m %N' {} | sort -rn | head -1 | cut -d' ' -f2-)
if [ -n "$DOC" ]; then
  echo "Found updated rules document: $DOC"
  cp rules_current.md rules_current.md.bak
  awk '/^## Appendix A/{exit} 1' rules_current.md > /tmp/mortalis_core_before.txt
  cp "$DOC" rules_current.md
  if python3 build_data.py; then
    rm -f rules_current.md.bak
    # The doc is now the source of truth — clear older published in-app edits
    printf '%s\n' \
      "// Published playtest data. Regenerated by 'Publish update.command'." \
      "// (Cleared: the rules document is currently the source of truth.)" > custom.js
    DOC_IMPORTED="$DOC"
    echo "Card database, rule text, and game constants rebuilt from the document."
    # Warn when CORE rule text (before the card appendices) changed — constants
    # apply automatically, but brand-new MECHANICS may need engine code.
    awk '/^## Appendix A/{exit} 1' rules_current.md > /tmp/mortalis_core_after.txt
    if ! diff -q /tmp/mortalis_core_before.txt /tmp/mortalis_core_after.txt >/dev/null 2>&1; then
      echo ""
      echo "⚠️  Core rule text changed in this update:"
      diff /tmp/mortalis_core_before.txt /tmp/mortalis_core_after.txt | grep '^[<>]' | head -14 | sed 's/^</   - removed:/; s/^>/   + added:  /'
      echo ""
      echo "   Numeric values (Mortality, Pulse, lane unlock turns, Overkill cap, ...)"
      echo "   were applied automatically. If a change introduces a brand-new MECHANIC,"
      echo "   play a quick game to check it — if the program doesn't follow the new"
      echo "   rule, bring it to Claude Code."
    fi
  else
    echo ""
    echo "❌ The document's card format has changed and the parser choked (see above)."
    echo "   Nothing was published. Ask Claude Code to update the parser."
    mv rules_current.md.bak rules_current.md
    read -k 1 "?Press any key to close..."
    exit 1
  fi
fi

# 2. Newest in-app export — used only if newer than the imported doc
NEWEST=$(ls -t ~/Downloads/mortalis_playtest_data*.json 2>/dev/null | head -1)
if [ -n "$NEWEST" ] && { [ ! -f custom.js ] || [ "$NEWEST" -nt custom.js ]; } && { [ -z "$DOC_IMPORTED" ] || [ "$NEWEST" -nt "$DOC_IMPORTED" ]; }; then
  echo "Using your exported in-app edits: $NEWEST"
  python3 - "$NEWEST" <<'PY'
import json, sys
data = json.load(open(sys.argv[1]))
assert data.get("cards"), "not a Mortalis export"
open("custom.js", "w").write(
    "// Published playtest data — generated by 'Publish update.command'.\n"
    "window.CUSTOM_DATA = " + json.dumps(data, ensure_ascii=False) + ";\n")
print(f"custom.js updated ({len(data['cards'])} cards).")
PY
  if [ $? -ne 0 ]; then echo "Could not read the export — skipping it."; fi
fi

# 3. Keep the send-to-a-friend single file in sync
python3 build_single_file.py

# 4. Push to GitHub (new local edits AND any already-committed but unpushed work,
#    e.g. commits made by Claude in Cowork sessions)
git add -A
if ! git diff --cached --quiet; then
  git commit -m "Playtest update $(date '+%Y-%m-%d %H:%M')" >/dev/null
fi
if [ -z "$(git log @{u}.. --oneline 2>/dev/null)" ]; then
  echo "Nothing changed since the last publish."
else
  if git push; then
    echo ""
    echo "✅ Published! The shared link updates in a minute or two:"
    git remote get-url origin | sed -E 's#(git@github.com:|https://github.com/)([^/]+)/([^.]+)(\.git)?#   https://\2.github.io/\3/#'
    echo "   (Playtesters may need a hard refresh: Cmd+Shift+R)"
  else
    echo "❌ Push failed — check your internet connection and try again."
  fi
fi
echo ""
read -k 1 "?Press any key to close..."
